name: init_architecture
description: >-
  CLI utility will generate folder architecture to help you and save your time when creating the first Flutter project.
version: 0.1.5
homepage: https://github.com/anwar907/init_architecture

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  init: init_architecture
